swagger: '2.0'
info:
  title: API Compte personnel d'activité
  description: "Récupération des données du salarié : formation, retraite, chomage"
  version: 0.0.1
basePath: /api
schemes:
  - http
  - https
produces:
  - application/json
paths:
  /cpa/{nir}/chomage:
    get:
      summary: Récupération des cotisations chomage d'un salarié
      parameters:
        - name: nir
          in: path
          description: numéro de securité sociale
          required: true
          type: number
          format: integer
          minimum: 99999999999999
          maximum: 1000000000000000
      tags:
        - Avec le NIR
      responses:
        '200':
          description: cotisation chomage
          schema:
            $ref: '#/definitions/Chomage'
        '404':
          description: 'Le Nir ne correspond à personne'
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /cpa/{nir}/retraite:
    get:
      summary: Récupération des cotisations aurpès de la retraite d'un salarié
      parameters:
        - name: nir
          in: path
          description: numéro de securité sociale
          required: true
          type: number
          format: integer
          minimum: 99999999999999
          maximum: 1000000000000000
      tags:
        - Avec le NIR
      responses:
        '200':
          description: cotisation retraite
          schema:
            $ref: '#/definitions/Retraite'
        '404':
          description: 'Le Nir ne correspond à personne'
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /cpa/{nir}/formation:
    get:
      summary: Récupération des crédits formation d'un salarié
      parameters:
        - name: nir
          in: path
          description: numéro de securité sociale
          required: true
          type: number
          format: integer
          minimum: 99999999999999
          maximum: 1000000000000000
      tags:
        - Avec le NIR
      responses:
        '200':
          description: crédit formation
          schema:
            $ref: '#/definitions/Formation'
        '404':
          description: 'Le Nir ne correspond à personne'
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /fc/chomage:
    get:
      summary: Récupération des cotisations chomage d'un salarié
      parameters:
        - name: token
          in: query
          description: token d'accès France Connect
          required: true
          type: string
      tags:
        - Avec FranceConnect
      responses:
        '200':
          description: cotisation chomage
          schema:
            $ref: '#/definitions/Chomage'
        '404':
          description: 'Le Nir ne correspond à personne'
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /fc/retraite:
    get:
      summary: Récupération des cotisations aurpès de la retraite d'un salarié
      parameters:
        - name: token
          in: query
          description: token d'accès France Connect
          required: true
          type: string
      tags:
        - Avec FranceConnect
      responses:
        '200':
          description: cotisation retraite
          schema:
            $ref: '#/definitions/Retraite'
        '404':
          description: 'Le Nir ne correspond à personne'
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /fc/formation:
    get:
      summary: Récupération des crédits formation d'un salarié
      parameters:
        - name: token
          in: query
          description: token d'accès France Connect
          required: true
          type: string
      tags:
        - Avec FranceConnect
      responses:
        '200':
          description: crédit formation
          schema:
            $ref: '#/definitions/Formation'
        '404':
          description: 'Le Nir ne correspond à personne'
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'


  /identitepivot/chomage:
    get:
      summary: Récupération des cotisations chomage d'un salarié
      parameters:
        - name: given_name
          in: query
          description: prénoms séparés par des espaces
          required: true
          type: string
        - name: family_name
          in: query
          description: le nom de famille de naissance
          required: true
          type: string
        - name: birthdate
          in: query
          description: la date de naissance au format YYYY-MM-DD
          required: true
          type: string
        - name: gender
          in: query
          description: male pour les hommes, female pour les femmes
          required: true
          type: string
        - name: birthplace
          in: query
          description: le code INSEE du lieu de naissance (ou une chaîne vide si la personne est née à l'étranger)
          required: true
          type: string
        - name: birthdepartment
          in: query
          description: le code INSEE du pays de naissance
          required: true
          type: string

      tags:
        - Avec l'identité pivot
      responses:
        '200':
          description: cotisation chomage
          schema:
            $ref: '#/definitions/Chomage'
        '404':
          description: 'Le Nir ne correspond à personne'
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /identitepivot/retraite:
    get:
      summary: Récupération des cotisations aurpès de la retraite d'un salarié
      parameters:
        - name: given_name
          in: query
          description: prénoms séparés par des espaces
          required: true
          type: string
        - name: family_name
          in: query
          description: le nom de famille de naissance
          required: true
          type: string
        - name: birthdate
          in: query
          description: la date de naissance au format YYYY-MM-DD
          required: true
          type: string
        - name: gender
          in: query
          description: male pour les hommes, female pour les femmes
          required: true
          type: string
        - name: birthplace
          in: query
          description: le code INSEE du lieu de naissance (ou une chaîne vide si la personne est née à l'étranger)
          required: true
          type: string
        - name: birthdepartment
          in: query
          description: le code INSEE du pays de naissance
          required: true
          type: string
      tags:
        - Avec l'identité pivot
      responses:
        '200':
          description: cotisation retraite
          schema:
            $ref: '#/definitions/Retraite'
        '404':
          description: 'Le Nir ne correspond à personne'
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /identitepivot/formation:
    get:
      summary: Récupération des crédits formation d'un salarié
      parameters:
        - name: given_name
          in: query
          description: prénoms séparés par des espaces
          required: true
          type: string
        - name: family_name
          in: query
          description: le nom de famille de naissance
          required: true
          type: string
        - name: birthdate
          in: query
          description: la date de naissance au format YYYY-MM-DD
          required: true
          type: string
        - name: gender
          in: query
          description: male pour les hommes, female pour les femmes
          required: true
          type: string
        - name: birthplace
          in: query
          description: le code INSEE du lieu de naissance (ou une chaîne vide si la personne est née à l'étranger)
          required: true
          type: string
        - name: birthdepartment
          in: query
          description: le code INSEE du pays de naissance
          required: true
          type: string
      tags:
        - Avec l'identité pivot
      responses:
        '200':
          description: crédit formation
          schema:
            $ref: '#/definitions/Formation'
        '404':
          description: 'Le Nir ne correspond à personne'
          schema:
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:
  identitepivot:
    type: object
    properties:
      family_name:
        type: string
        description: nom de famille
      given_name:
        type: string
        description: prénom
      birthdate:
        type: string
        description: date de naissance (JJ/MM/YYYY)
      gender:
        type: string
        description: male ou Female
      birthdepartement:
        type: string
        description: Departement de naissance
      birthplace:
        type: string
        description: ville de naissance
      birthcountry:
        type: string
        description: pays d'origine

  Chomage:
      type: object
      properties:
        id:
          type: string
          description: NIR
        identite:
          $ref: '#/definitions/identitepivot'
        emplois:
          type: array
          items:
            type: object
            properties:
              employeur:
                type: object
                properties:
                  nom:
                    type: string
                    description: nom de famille
                  ville:
                    type: string
                    description: ville
                  codepostal:
                    type: string
                    description: code postal
                  siret:
                    type: string
                    description: siret
                  ape:
                    type: string
                    description: APE/NAF
              details:
                type: array
                items:
                  type: object
                  properties:
                    date:
                      type: string
                      description: date
                    debut:
                      type: string
                      description: debut
                    fin:
                      type: string
                      description: fin
                    heuretravaillé:
                      type: string
                      description: nombres d'heures travaillé
                    salairebrut:
                      type: string
                      description: salaire brut
                    precomptepoleemploi:
                      type: string
                      description: precompte pole emploi

  Retraite:
      type: object
      properties:
        id:
          type: string
          description: NIR
        identite:
          $ref: '#/definitions/identitepivot'
        retraitedebase:
          type: object
          properties:
            trimestrestotal:
              type: string
              description: trimestre total
            pointtotal:
              type: string
              description: point total
            regimes:
              type: array
              items:
                type: object
                properties:
                  typeregime:
                    type: string
                    description: type de regime
                  nombretrimestre:
                    type: string
                    description: nombre de trimestres
                  derniereannee:
                    type: string
                    description: derniere annee
                  points:
                    type: string
                    description: points
                  details:
                    type: array
                    items:
                      type: object
                      properties:
                        annee:
                          type: string
                          description: annee
                        debut:
                          type: string
                          description: debut
                        fin:
                          type: string
                          description: fin
                        specifiques:
                          type: object
                          properties:
                            employeur:
                              type: string
                              description: employeur
                            salaireannuel:
                              type: string
                              description: salaire annuel
                            trimestres:
                              type: string
                              description: trimestres
        retraitecomplementaire:
          type: object
          properties:
            trimestrestotal:
              type: string
              description: trimestre total
            pointtotal:
              type: string
              description: point total
            regimes:
              type: array
              items:
                type: object
                properties:
                  typeregime:
                    type: string
                    description: type de regime
                  nombretrimestre:
                    type: string
                    description: nombre de trimestres
                  derniereannee:
                    type: string
                    description: derniere annee
                  points:
                    type: string
                    description: points
                  details:
                    type: array
                    items:
                      type: object
                      properties:
                        annee:
                          type: string
                          description: annee
                        debut:
                          type: string
                          description: debut
                        fin:
                          type: string
                          description: fin
                        specifiques:
                          type: object
                          properties:
                            employeur:
                              type: string
                              description: employeur
                            salaireannuel:
                              type: string
                              description: salaire annuel
                            trimestres:
                              type: string
                              description: trimestres

  Formation:
    type: object
    properties:
      id:
        type: string
        description: NIR
      identite:
        $ref: '#/definitions/identitepivot'
      compteheure:
        type: object
        properties:
          solde:
            type: string
            description: solde
          credits:
            type: array
            items:
              type: object
              properties:
                valeur:
                  type: string
                  description: valeur
                date:
                  type: string
                  description: date
                debut:
                  type: string
                  description: debut
                fin:
                  type: string
                  description: fin
                entreprise:
                  type: object
                  properties:
                    nom:
                      type: string
                      description: nom
                    siret:
                      type: string
                      description: siret
          debits:
            type: array
            items:
              type: object
              properties:
                status:
                  type: string
                  description: status
                date:
                  type: string
                  description: date
                formation:
                  type: object
                  properties:
                    nom:
                      type: string
                      description: nom
                    id:
                      type: string
                      description: id
                    editeur:
                      type: string
                      description: editeur
                    niveau:
                      type: string
                      description: niveau
                    ape:
                      type: string
                      description: ape

  Error:
    type: object
